### ISSUE TITLE
2023 NeurIPS paper - Scaling Data-Constrained Language Models

### ISSUE THREAD

**Issue by BounharAbdelaziz** [MoroccoAI/Moroccans-top-AI-confs#1]
Another **2023** NeurIPS paper by Niklas Muennighoff, Alexander Rush, Boaz Barak, Teven Le Scao, **Nouamane Tazi**, Aleksandra Piktus, Sampo Pyysalo, Thomas Wolf, Colin A. Raffel [Scaling Data-Constrained Language Models](https://proceedings.neurips.cc/paper_files/paper/2023/file/9d89448b63ce1e2e8dc7af72c984c196-Paper-Conference.pdf). This paper also received the prestigious **best paper award**!

**Comment by redouanelg** [comment]
@BounharAbdelaziz oh man, I have even congratulated Nouamane in person on behalf of MoroccoAI..

The plan was to add a section "hall of fame" and put his paper there, thanks for the reminder !

**Comment by redouanelg** [comment]
Done

**Comment by BounharAbdelaziz** [comment]
No problem, it happens! Considering the multitude of papers you included, it's understandable. Great job!
The hall of fame section is a great idea.
